# Generated by Django 5.0.1 on 2024-03-13 21:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('book_table', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='discount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
            preserve_default=False,
        ),
    ]
