# Generated by Django 5.0.1 on 2024-03-28 16:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('book_table', '0002_voucher_discount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Voucher',
        ),
    ]
