# Generated by Django 5.0.1 on 2024-03-13 11:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('book_table', '0002_customer_delete_tablebookings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vouchers',
            new_name='Voucher',
        ),
    ]
