# Generated by Django 5.0.1 on 2024-02-09 13:02

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChefSpecials',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('ingredients', models.JSONField(default=list)),
                ('served', models.IntegerField(choices=[(0, 'Breakfast'), (1, 'Lunch'), (2, 'Supper')], default=0)),
                ('featured_image',
                 cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['served', 'created_at'],
            },
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
