# Generated by Django 5.0.1 on 2024-03-13 11:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0002_remove_chefspecial_ingredients_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
