# Generated by Django 5.0.1 on 2024-02-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0002_chefspecials_alter_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chefspecials',
            name='ingredients',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
