# Generated by Django 5.0.1 on 2024-02-09 13:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0003_alter_chefspecials_ingredients'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChefSpecials',
            new_name='ChefSpecial',
        ),
    ]
