# Generated by Django 5.0.1 on 2024-02-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0004_rename_chefspecials_chefspecial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chefspecial',
            name='ingredients',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
