# Generated by Django 5.0.1 on 2024-02-15 13:03

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0005_alter_chefspecial_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chefspecial',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='chefspecial',
            name='ingredients',
            field=models.JSONField(default=list),
        ),
    ]
