# Generated by Django 5.0.1 on 2024-03-02 23:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='ingredients',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_type',
            field=models.IntegerField(choices=[(0, 'Breakfast'), (1, 'Lunch'), (2, 'Supper')], default=0),
        ),
    ]
