# Generated by Django 5.0.1 on 2024-03-03 15:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('menu', '0002_alter_menu_ingredients_alter_menu_menu_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='ingredients',
            new_name='description',
        ),
    ]
