# Generated by Django 5.0.1 on 2024-03-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('menu', '0003_rename_ingredients_menu_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_type',
            field=models.IntegerField(
                choices=[(0, 'Breakfast'), (1, 'Lunch'), (2, 'Supper'), (3, 'alcohol'), (4, 'starter')], default=0),
        ),
    ]
